package com.example.psk1.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Animal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.ANIMALNAME
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    private String animalname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANIMAL.BARN_ID
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    private Long barnId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.ID
     *
     * @return the value of PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.ID
     *
     * @param id the value for PUBLIC.ANIMAL.ID
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.ANIMALNAME
     *
     * @return the value of PUBLIC.ANIMAL.ANIMALNAME
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    public String getAnimalname() {
        return animalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.ANIMALNAME
     *
     * @param animalname the value for PUBLIC.ANIMAL.ANIMALNAME
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    public void setAnimalname(String animalname) {
        this.animalname = animalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANIMAL.BARN_ID
     *
     * @return the value of PUBLIC.ANIMAL.BARN_ID
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    public Long getBarnId() {
        return barnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANIMAL.BARN_ID
     *
     * @param barnId the value for PUBLIC.ANIMAL.BARN_ID
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    public void setBarnId(Long barnId) {
        this.barnId = barnId;
    }
}