package com.example.psk1.mybatis.model;

public class Worker {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKER.ID
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WORKER.NAME
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKER.ID
     *
     * @return the value of PUBLIC.WORKER.ID
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKER.ID
     *
     * @param id the value for PUBLIC.WORKER.ID
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WORKER.NAME
     *
     * @return the value of PUBLIC.WORKER.NAME
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WORKER.NAME
     *
     * @param name the value for PUBLIC.WORKER.NAME
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}