package com.example.psk1.mybatis.dao;

import com.example.psk1.mybatis.model.Animal;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface AnimalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ANIMAL
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ANIMAL
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    int insert(Animal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ANIMAL
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    Animal selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ANIMAL
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    List<Animal> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ANIMAL
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    int updateByPrimaryKey(Animal record);
}