package com.example.psk1.mybatis.dao;

import com.example.psk1.mybatis.model.Barn;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface BarnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BARN
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BARN
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    int insert(Barn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BARN
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    Barn selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BARN
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    List<Barn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BARN
     *
     * @mbg.generated Fri Apr 01 14:19:59 EEST 2022
     */
    int updateByPrimaryKey(Barn record);
}